apiVersion: v1
kind: Service
metadata:
  namespace: three-tier
# this name always match to the backend/deployment.yaml env variable MONGO_CONN_STR 
  name: mongodb-svc  
spec:
  selector:
    app: mongodb
  ports:
  - name: mongodb-svc
    protocol: TCP
    port: 27017
    targetPort: 27017


